### ISSUE TITLE
Drawer playground not displaying default nav item font color in dark theme view

### ISSUE THREAD

**Issue by jvgreiner** [etn-ccis/blui-react-native#119]
#### What are the steps to reproduce?

1. Go to https://brightlayer-ui-components.github.io/react-native-dev/components/drawer/playground
2. Click on settings gear and select dark theme

#### Screenshots / Screen recording
![image](https://github.com/user-attachments/assets/0261adbe-4181-4747-8305-5bea883614d1)

#### Code snippet / Link to minimum reproduction example

```
CODE HERE
```

**Comment by shubham-eaton** [comment]
This is fixed and should be available in next release of component library.

**Comment by huayunh** [comment]
This is not fixed, and the active item is now showing its selected state either. Looking at this, nobody would know which item is currently selected

![Image](https://github.com/user-attachments/assets/9e0d9fc6-a53d-49c9-bbc8-25c329b4df5c)
